/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ng2-nvd3';
export const NvD3ModuleNgFactory:i0.NgModuleFactory<i1.NvD3Module> = i0.ɵcmf(i1.NvD3Module,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(512,
          i1.NvD3Module,i1.NvD3Module,([] as any[]))]);
    });
const styles_nvD3:any[] = ['\n          nvd3 {\n            display: block;\n            width: 100%;\n          }\n        '];
export const RenderType_nvD3:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_nvD3,
    data:{}});
export function View_nvD3_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,([] as any[]),(null as any),(null as any));
}
export function View_nvD3_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'nvd3',([] as any[]),
      (null as any),(null as any),(null as any),View_nvD3_0,RenderType_nvD3)),i0.ɵdid(573440,
      (null as any),0,i1.nvD3,[i0.ElementRef],(null as any),(null as any))],(null as any),
      (null as any));
}
export const nvD3NgFactory:i0.ComponentFactory<i1.nvD3> = i0.ɵccf('nvd3',i1.nvD3,View_nvD3_Host_0,
    {options:'options',data:'data'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRTovU2FuZy9Qcm9qZWN0cy9uZzItbnZkMy9zcmMvbGliL25nMi1udmQzLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0U6L1NhbmcvUHJvamVjdHMvbmcyLW52ZDMvc3JjL2xpYi9uZzItbnZkMy50cyIsIm5nOi8vL0U6L1NhbmcvUHJvamVjdHMvbmcyLW52ZDMvc3JjL2xpYi9uZzItbnZkMy50cy5udkQzX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPG52ZDM+PC9udmQzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsK0VBQUE7TUFBQTs7OzsifQ==
